// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moviesearcher.proto

package com.doubleknd26.moviesearcher.proto;

public interface MovieInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string director = 2;</code>
   */
  java.lang.String getDirector();
  /**
   * <code>string director = 2;</code>
   */
  com.google.protobuf.ByteString
      getDirectorBytes();

  /**
   * <code>repeated string starring = 3;</code>
   */
  java.util.List<java.lang.String>
      getStarringList();
  /**
   * <code>repeated string starring = 3;</code>
   */
  int getStarringCount();
  /**
   * <code>repeated string starring = 3;</code>
   */
  java.lang.String getStarring(int index);
  /**
   * <code>repeated string starring = 3;</code>
   */
  com.google.protobuf.ByteString
      getStarringBytes(int index);

  /**
   * <code>repeated string genre = 4;</code>
   */
  java.util.List<java.lang.String>
      getGenreList();
  /**
   * <code>repeated string genre = 4;</code>
   */
  int getGenreCount();
  /**
   * <code>repeated string genre = 4;</code>
   */
  java.lang.String getGenre(int index);
  /**
   * <code>repeated string genre = 4;</code>
   */
  com.google.protobuf.ByteString
      getGenreBytes(int index);

  /**
   * <code>double grade = 5;</code>
   */
  double getGrade();

  /**
   * <code>int64 release_time = 6;</code>
   */
  long getReleaseTime();

  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  java.util.List<com.doubleknd26.moviesearcher.proto.Review> 
      getReviewsList();
  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  com.doubleknd26.moviesearcher.proto.Review getReviews(int index);
  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  int getReviewsCount();
  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  java.util.List<? extends com.doubleknd26.moviesearcher.proto.ReviewOrBuilder> 
      getReviewsOrBuilderList();
  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  com.doubleknd26.moviesearcher.proto.ReviewOrBuilder getReviewsOrBuilder(
      int index);
}
