// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moving.proto

package com.doubleknd26.moving.proto;

/**
 * Protobuf type {@code MovieInfo}
 */
public  final class MovieInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MovieInfo)
    MovieInfoOrBuilder {
  // Use MovieInfo.newBuilder() to construct.
  private MovieInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MovieInfo() {
    title_ = "";
    director_ = "";
    starring_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    genre_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    grade_ = 0D;
    releaseTime_ = 0L;
    reviews_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MovieInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            director_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              starring_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            starring_.add(s);
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              genre_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            genre_.add(s);
            break;
          }
          case 41: {

            grade_ = input.readDouble();
            break;
          }
          case 48: {

            releaseTime_ = input.readInt64();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              reviews_ = new java.util.ArrayList<com.doubleknd26.moving.proto.Review>();
              mutable_bitField0_ |= 0x00000040;
            }
            reviews_.add(
                input.readMessage(com.doubleknd26.moving.proto.Review.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        starring_ = starring_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        genre_ = genre_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        reviews_ = java.util.Collections.unmodifiableList(reviews_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.doubleknd26.moving.proto.Moving.internal_static_MovieInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.doubleknd26.moving.proto.Moving.internal_static_MovieInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.doubleknd26.moving.proto.MovieInfo.class, com.doubleknd26.moving.proto.MovieInfo.Builder.class);
  }

  private int bitField0_;
  public static final int TITLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object title_;
  /**
   * <code>optional string title = 1;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>optional string title = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTOR_FIELD_NUMBER = 2;
  private volatile java.lang.Object director_;
  /**
   * <code>optional string director = 2;</code>
   */
  public java.lang.String getDirector() {
    java.lang.Object ref = director_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      director_ = s;
      return s;
    }
  }
  /**
   * <code>optional string director = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDirectorBytes() {
    java.lang.Object ref = director_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      director_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARRING_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList starring_;
  /**
   * <code>repeated string starring = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getStarringList() {
    return starring_;
  }
  /**
   * <code>repeated string starring = 3;</code>
   */
  public int getStarringCount() {
    return starring_.size();
  }
  /**
   * <code>repeated string starring = 3;</code>
   */
  public java.lang.String getStarring(int index) {
    return starring_.get(index);
  }
  /**
   * <code>repeated string starring = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStarringBytes(int index) {
    return starring_.getByteString(index);
  }

  public static final int GENRE_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList genre_;
  /**
   * <code>repeated string genre = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getGenreList() {
    return genre_;
  }
  /**
   * <code>repeated string genre = 4;</code>
   */
  public int getGenreCount() {
    return genre_.size();
  }
  /**
   * <code>repeated string genre = 4;</code>
   */
  public java.lang.String getGenre(int index) {
    return genre_.get(index);
  }
  /**
   * <code>repeated string genre = 4;</code>
   */
  public com.google.protobuf.ByteString
      getGenreBytes(int index) {
    return genre_.getByteString(index);
  }

  public static final int GRADE_FIELD_NUMBER = 5;
  private double grade_;
  /**
   * <code>optional double grade = 5;</code>
   */
  public double getGrade() {
    return grade_;
  }

  public static final int RELEASE_TIME_FIELD_NUMBER = 6;
  private long releaseTime_;
  /**
   * <code>optional int64 release_time = 6;</code>
   */
  public long getReleaseTime() {
    return releaseTime_;
  }

  public static final int REVIEWS_FIELD_NUMBER = 7;
  private java.util.List<com.doubleknd26.moving.proto.Review> reviews_;
  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  public java.util.List<com.doubleknd26.moving.proto.Review> getReviewsList() {
    return reviews_;
  }
  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  public java.util.List<? extends com.doubleknd26.moving.proto.ReviewOrBuilder> 
      getReviewsOrBuilderList() {
    return reviews_;
  }
  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  public int getReviewsCount() {
    return reviews_.size();
  }
  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  public com.doubleknd26.moving.proto.Review getReviews(int index) {
    return reviews_.get(index);
  }
  /**
   * <code>repeated .Review reviews = 7;</code>
   */
  public com.doubleknd26.moving.proto.ReviewOrBuilder getReviewsOrBuilder(
      int index) {
    return reviews_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
    }
    if (!getDirectorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, director_);
    }
    for (int i = 0; i < starring_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, starring_.getRaw(i));
    }
    for (int i = 0; i < genre_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, genre_.getRaw(i));
    }
    if (grade_ != 0D) {
      output.writeDouble(5, grade_);
    }
    if (releaseTime_ != 0L) {
      output.writeInt64(6, releaseTime_);
    }
    for (int i = 0; i < reviews_.size(); i++) {
      output.writeMessage(7, reviews_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
    }
    if (!getDirectorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, director_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < starring_.size(); i++) {
        dataSize += computeStringSizeNoTag(starring_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStarringList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < genre_.size(); i++) {
        dataSize += computeStringSizeNoTag(genre_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getGenreList().size();
    }
    if (grade_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, grade_);
    }
    if (releaseTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, releaseTime_);
    }
    for (int i = 0; i < reviews_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, reviews_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.doubleknd26.moving.proto.MovieInfo)) {
      return super.equals(obj);
    }
    com.doubleknd26.moving.proto.MovieInfo other = (com.doubleknd26.moving.proto.MovieInfo) obj;

    boolean result = true;
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getDirector()
        .equals(other.getDirector());
    result = result && getStarringList()
        .equals(other.getStarringList());
    result = result && getGenreList()
        .equals(other.getGenreList());
    result = result && (
        java.lang.Double.doubleToLongBits(getGrade())
        == java.lang.Double.doubleToLongBits(
            other.getGrade()));
    result = result && (getReleaseTime()
        == other.getReleaseTime());
    result = result && getReviewsList()
        .equals(other.getReviewsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + DIRECTOR_FIELD_NUMBER;
    hash = (53 * hash) + getDirector().hashCode();
    if (getStarringCount() > 0) {
      hash = (37 * hash) + STARRING_FIELD_NUMBER;
      hash = (53 * hash) + getStarringList().hashCode();
    }
    if (getGenreCount() > 0) {
      hash = (37 * hash) + GENRE_FIELD_NUMBER;
      hash = (53 * hash) + getGenreList().hashCode();
    }
    hash = (37 * hash) + GRADE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getGrade()));
    hash = (37 * hash) + RELEASE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReleaseTime());
    if (getReviewsCount() > 0) {
      hash = (37 * hash) + REVIEWS_FIELD_NUMBER;
      hash = (53 * hash) + getReviewsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.doubleknd26.moving.proto.MovieInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.doubleknd26.moving.proto.MovieInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.doubleknd26.moving.proto.MovieInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.doubleknd26.moving.proto.MovieInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.doubleknd26.moving.proto.MovieInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.doubleknd26.moving.proto.MovieInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.doubleknd26.moving.proto.MovieInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.doubleknd26.moving.proto.MovieInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.doubleknd26.moving.proto.MovieInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.doubleknd26.moving.proto.MovieInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.doubleknd26.moving.proto.MovieInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MovieInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MovieInfo)
      com.doubleknd26.moving.proto.MovieInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.doubleknd26.moving.proto.Moving.internal_static_MovieInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.doubleknd26.moving.proto.Moving.internal_static_MovieInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.doubleknd26.moving.proto.MovieInfo.class, com.doubleknd26.moving.proto.MovieInfo.Builder.class);
    }

    // Construct using com.doubleknd26.moving.proto.MovieInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getReviewsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      title_ = "";

      director_ = "";

      starring_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      genre_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      grade_ = 0D;

      releaseTime_ = 0L;

      if (reviewsBuilder_ == null) {
        reviews_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        reviewsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.doubleknd26.moving.proto.Moving.internal_static_MovieInfo_descriptor;
    }

    public com.doubleknd26.moving.proto.MovieInfo getDefaultInstanceForType() {
      return com.doubleknd26.moving.proto.MovieInfo.getDefaultInstance();
    }

    public com.doubleknd26.moving.proto.MovieInfo build() {
      com.doubleknd26.moving.proto.MovieInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.doubleknd26.moving.proto.MovieInfo buildPartial() {
      com.doubleknd26.moving.proto.MovieInfo result = new com.doubleknd26.moving.proto.MovieInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.title_ = title_;
      result.director_ = director_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        starring_ = starring_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.starring_ = starring_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        genre_ = genre_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.genre_ = genre_;
      result.grade_ = grade_;
      result.releaseTime_ = releaseTime_;
      if (reviewsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          reviews_ = java.util.Collections.unmodifiableList(reviews_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.reviews_ = reviews_;
      } else {
        result.reviews_ = reviewsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.doubleknd26.moving.proto.MovieInfo) {
        return mergeFrom((com.doubleknd26.moving.proto.MovieInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.doubleknd26.moving.proto.MovieInfo other) {
      if (other == com.doubleknd26.moving.proto.MovieInfo.getDefaultInstance()) return this;
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getDirector().isEmpty()) {
        director_ = other.director_;
        onChanged();
      }
      if (!other.starring_.isEmpty()) {
        if (starring_.isEmpty()) {
          starring_ = other.starring_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureStarringIsMutable();
          starring_.addAll(other.starring_);
        }
        onChanged();
      }
      if (!other.genre_.isEmpty()) {
        if (genre_.isEmpty()) {
          genre_ = other.genre_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureGenreIsMutable();
          genre_.addAll(other.genre_);
        }
        onChanged();
      }
      if (other.getGrade() != 0D) {
        setGrade(other.getGrade());
      }
      if (other.getReleaseTime() != 0L) {
        setReleaseTime(other.getReleaseTime());
      }
      if (reviewsBuilder_ == null) {
        if (!other.reviews_.isEmpty()) {
          if (reviews_.isEmpty()) {
            reviews_ = other.reviews_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureReviewsIsMutable();
            reviews_.addAll(other.reviews_);
          }
          onChanged();
        }
      } else {
        if (!other.reviews_.isEmpty()) {
          if (reviewsBuilder_.isEmpty()) {
            reviewsBuilder_.dispose();
            reviewsBuilder_ = null;
            reviews_ = other.reviews_;
            bitField0_ = (bitField0_ & ~0x00000040);
            reviewsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReviewsFieldBuilder() : null;
          } else {
            reviewsBuilder_.addAllMessages(other.reviews_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.doubleknd26.moving.proto.MovieInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.doubleknd26.moving.proto.MovieInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object title_ = "";
    /**
     * <code>optional string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string title = 1;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 1;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 1;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object director_ = "";
    /**
     * <code>optional string director = 2;</code>
     */
    public java.lang.String getDirector() {
      java.lang.Object ref = director_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        director_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string director = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDirectorBytes() {
      java.lang.Object ref = director_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        director_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string director = 2;</code>
     */
    public Builder setDirector(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      director_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string director = 2;</code>
     */
    public Builder clearDirector() {
      
      director_ = getDefaultInstance().getDirector();
      onChanged();
      return this;
    }
    /**
     * <code>optional string director = 2;</code>
     */
    public Builder setDirectorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      director_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList starring_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureStarringIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        starring_ = new com.google.protobuf.LazyStringArrayList(starring_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string starring = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStarringList() {
      return starring_.getUnmodifiableView();
    }
    /**
     * <code>repeated string starring = 3;</code>
     */
    public int getStarringCount() {
      return starring_.size();
    }
    /**
     * <code>repeated string starring = 3;</code>
     */
    public java.lang.String getStarring(int index) {
      return starring_.get(index);
    }
    /**
     * <code>repeated string starring = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStarringBytes(int index) {
      return starring_.getByteString(index);
    }
    /**
     * <code>repeated string starring = 3;</code>
     */
    public Builder setStarring(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStarringIsMutable();
      starring_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string starring = 3;</code>
     */
    public Builder addStarring(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStarringIsMutable();
      starring_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string starring = 3;</code>
     */
    public Builder addAllStarring(
        java.lang.Iterable<java.lang.String> values) {
      ensureStarringIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, starring_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string starring = 3;</code>
     */
    public Builder clearStarring() {
      starring_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string starring = 3;</code>
     */
    public Builder addStarringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureStarringIsMutable();
      starring_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList genre_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureGenreIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        genre_ = new com.google.protobuf.LazyStringArrayList(genre_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getGenreList() {
      return genre_.getUnmodifiableView();
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public int getGenreCount() {
      return genre_.size();
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public java.lang.String getGenre(int index) {
      return genre_.get(index);
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGenreBytes(int index) {
      return genre_.getByteString(index);
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public Builder setGenre(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureGenreIsMutable();
      genre_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public Builder addGenre(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureGenreIsMutable();
      genre_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public Builder addAllGenre(
        java.lang.Iterable<java.lang.String> values) {
      ensureGenreIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, genre_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public Builder clearGenre() {
      genre_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public Builder addGenreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureGenreIsMutable();
      genre_.add(value);
      onChanged();
      return this;
    }

    private double grade_ ;
    /**
     * <code>optional double grade = 5;</code>
     */
    public double getGrade() {
      return grade_;
    }
    /**
     * <code>optional double grade = 5;</code>
     */
    public Builder setGrade(double value) {
      
      grade_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double grade = 5;</code>
     */
    public Builder clearGrade() {
      
      grade_ = 0D;
      onChanged();
      return this;
    }

    private long releaseTime_ ;
    /**
     * <code>optional int64 release_time = 6;</code>
     */
    public long getReleaseTime() {
      return releaseTime_;
    }
    /**
     * <code>optional int64 release_time = 6;</code>
     */
    public Builder setReleaseTime(long value) {
      
      releaseTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 release_time = 6;</code>
     */
    public Builder clearReleaseTime() {
      
      releaseTime_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.doubleknd26.moving.proto.Review> reviews_ =
      java.util.Collections.emptyList();
    private void ensureReviewsIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        reviews_ = new java.util.ArrayList<com.doubleknd26.moving.proto.Review>(reviews_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.doubleknd26.moving.proto.Review, com.doubleknd26.moving.proto.Review.Builder, com.doubleknd26.moving.proto.ReviewOrBuilder> reviewsBuilder_;

    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public java.util.List<com.doubleknd26.moving.proto.Review> getReviewsList() {
      if (reviewsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reviews_);
      } else {
        return reviewsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public int getReviewsCount() {
      if (reviewsBuilder_ == null) {
        return reviews_.size();
      } else {
        return reviewsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public com.doubleknd26.moving.proto.Review getReviews(int index) {
      if (reviewsBuilder_ == null) {
        return reviews_.get(index);
      } else {
        return reviewsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public Builder setReviews(
        int index, com.doubleknd26.moving.proto.Review value) {
      if (reviewsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReviewsIsMutable();
        reviews_.set(index, value);
        onChanged();
      } else {
        reviewsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public Builder setReviews(
        int index, com.doubleknd26.moving.proto.Review.Builder builderForValue) {
      if (reviewsBuilder_ == null) {
        ensureReviewsIsMutable();
        reviews_.set(index, builderForValue.build());
        onChanged();
      } else {
        reviewsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public Builder addReviews(com.doubleknd26.moving.proto.Review value) {
      if (reviewsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReviewsIsMutable();
        reviews_.add(value);
        onChanged();
      } else {
        reviewsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public Builder addReviews(
        int index, com.doubleknd26.moving.proto.Review value) {
      if (reviewsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReviewsIsMutable();
        reviews_.add(index, value);
        onChanged();
      } else {
        reviewsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public Builder addReviews(
        com.doubleknd26.moving.proto.Review.Builder builderForValue) {
      if (reviewsBuilder_ == null) {
        ensureReviewsIsMutable();
        reviews_.add(builderForValue.build());
        onChanged();
      } else {
        reviewsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public Builder addReviews(
        int index, com.doubleknd26.moving.proto.Review.Builder builderForValue) {
      if (reviewsBuilder_ == null) {
        ensureReviewsIsMutable();
        reviews_.add(index, builderForValue.build());
        onChanged();
      } else {
        reviewsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public Builder addAllReviews(
        java.lang.Iterable<? extends com.doubleknd26.moving.proto.Review> values) {
      if (reviewsBuilder_ == null) {
        ensureReviewsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reviews_);
        onChanged();
      } else {
        reviewsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public Builder clearReviews() {
      if (reviewsBuilder_ == null) {
        reviews_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        reviewsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public Builder removeReviews(int index) {
      if (reviewsBuilder_ == null) {
        ensureReviewsIsMutable();
        reviews_.remove(index);
        onChanged();
      } else {
        reviewsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public com.doubleknd26.moving.proto.Review.Builder getReviewsBuilder(
        int index) {
      return getReviewsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public com.doubleknd26.moving.proto.ReviewOrBuilder getReviewsOrBuilder(
        int index) {
      if (reviewsBuilder_ == null) {
        return reviews_.get(index);  } else {
        return reviewsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public java.util.List<? extends com.doubleknd26.moving.proto.ReviewOrBuilder> 
         getReviewsOrBuilderList() {
      if (reviewsBuilder_ != null) {
        return reviewsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reviews_);
      }
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public com.doubleknd26.moving.proto.Review.Builder addReviewsBuilder() {
      return getReviewsFieldBuilder().addBuilder(
          com.doubleknd26.moving.proto.Review.getDefaultInstance());
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public com.doubleknd26.moving.proto.Review.Builder addReviewsBuilder(
        int index) {
      return getReviewsFieldBuilder().addBuilder(
          index, com.doubleknd26.moving.proto.Review.getDefaultInstance());
    }
    /**
     * <code>repeated .Review reviews = 7;</code>
     */
    public java.util.List<com.doubleknd26.moving.proto.Review.Builder> 
         getReviewsBuilderList() {
      return getReviewsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.doubleknd26.moving.proto.Review, com.doubleknd26.moving.proto.Review.Builder, com.doubleknd26.moving.proto.ReviewOrBuilder> 
        getReviewsFieldBuilder() {
      if (reviewsBuilder_ == null) {
        reviewsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.doubleknd26.moving.proto.Review, com.doubleknd26.moving.proto.Review.Builder, com.doubleknd26.moving.proto.ReviewOrBuilder>(
                reviews_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        reviews_ = null;
      }
      return reviewsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:MovieInfo)
  }

  // @@protoc_insertion_point(class_scope:MovieInfo)
  private static final com.doubleknd26.moving.proto.MovieInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.doubleknd26.moving.proto.MovieInfo();
  }

  public static com.doubleknd26.moving.proto.MovieInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovieInfo>
      PARSER = new com.google.protobuf.AbstractParser<MovieInfo>() {
    public MovieInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MovieInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MovieInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MovieInfo> getParserForType() {
    return PARSER;
  }

  public com.doubleknd26.moving.proto.MovieInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

