// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moving.proto

package com.doubleknd26.moving.proto;

public final class Moving {
  private Moving() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Review_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Review_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014moving.proto\"x\n\006Review\022\037\n\nsourceType\030\001" +
      " \001(\0162\013.SourceType\022\013\n\003url\030\002 \001(\t\022\r\n\005title\030" +
      "\003 \001(\t\022\r\n\005grade\030\004 \001(\002\022\017\n\007comment\030\005 \001(\t\022\021\n" +
      "\ttimestamp\030\006 \001(\003\"\214\001\n\tMovieInfo\022\r\n\005title\030" +
      "\001 \001(\t\022\020\n\010director\030\002 \001(\t\022\020\n\010starring\030\003 \003(" +
      "\t\022\r\n\005genre\030\004 \003(\t\022\r\n\005grade\030\005 \001(\001\022\024\n\014relea" +
      "se_time\030\006 \001(\003\022\030\n\007reviews\030\007 \003(\0132\007.Review*" +
      "\027\n\nSourceType\022\t\n\005NAVER\020\000B \n\034com.doublekn" +
      "d26.moving.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Review_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Review_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Review_descriptor,
        new java.lang.String[] { "SourceType", "Url", "Title", "Grade", "Comment", "Timestamp", });
    internal_static_MovieInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MovieInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieInfo_descriptor,
        new java.lang.String[] { "Title", "Director", "Starring", "Genre", "Grade", "ReleaseTime", "Reviews", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
