// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moving.proto

package com.doubleknd26.moving.proto;

public interface ReviewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Review)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SourceType sourceType = 1;</code>
   */
  int getSourceTypeValue();
  /**
   * <code>.SourceType sourceType = 1;</code>
   */
  com.doubleknd26.moving.proto.SourceType getSourceType();

  /**
   * <code>string url = 2;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 2;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string title = 3;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>float grade = 4;</code>
   */
  float getGrade();

  /**
   * <code>string comment = 5;</code>
   */
  java.lang.String getComment();
  /**
   * <code>string comment = 5;</code>
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <code>int64 timestamp = 6;</code>
   */
  long getTimestamp();
}
