// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filmography.proto

package com.doubleknd26.filmography.proto;

public final class Filmography {
  private Filmography() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Review_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Review_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FilmInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FilmInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021filmography.proto\"p\n\006Review\022\r\n\005title\030\001" +
      " \001(\t\022\013\n\003url\030\002 \001(\t\022\r\n\005grade\030\003 \001(\002\022\017\n\007comm" +
      "ent\030\004 \001(\t\022\021\n\ttimestamp\030\005 \001(\003\022\027\n\006source\030c" +
      " \001(\0162\007.Source\"j\n\010FilmInfo\022\r\n\005title\030\001 \001(\t" +
      "\022\020\n\010ageLimit\030\002 \001(\t\022\021\n\timagePath\030\003 \001(\t\022\020\n" +
      "\010avgGrade\030\004 \001(\002\022\030\n\007reviews\030\005 \003(\0132\007.Revie" +
      "w*\035\n\006Source\022\010\n\004TEST\020\000\022\t\n\005NAVER\020\001B%\n!com." +
      "doubleknd26.filmography.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Review_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Review_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Review_descriptor,
        new java.lang.String[] { "Title", "Url", "Grade", "Comment", "Timestamp", "Source", });
    internal_static_FilmInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FilmInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FilmInfo_descriptor,
        new java.lang.String[] { "Title", "AgeLimit", "ImagePath", "AvgGrade", "Reviews", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
