// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filmography.proto

package com.doubleknd26.filmography.proto;

public interface FilmInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FilmInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string ageLimit = 2;</code>
   */
  java.lang.String getAgeLimit();
  /**
   * <code>string ageLimit = 2;</code>
   */
  com.google.protobuf.ByteString
      getAgeLimitBytes();

  /**
   * <code>string imagePath = 3;</code>
   */
  java.lang.String getImagePath();
  /**
   * <code>string imagePath = 3;</code>
   */
  com.google.protobuf.ByteString
      getImagePathBytes();

  /**
   * <code>float avgGrade = 4;</code>
   */
  float getAvgGrade();

  /**
   * <code>repeated .Review reviews = 5;</code>
   */
  java.util.List<com.doubleknd26.filmography.proto.Review> 
      getReviewsList();
  /**
   * <code>repeated .Review reviews = 5;</code>
   */
  com.doubleknd26.filmography.proto.Review getReviews(int index);
  /**
   * <code>repeated .Review reviews = 5;</code>
   */
  int getReviewsCount();
  /**
   * <code>repeated .Review reviews = 5;</code>
   */
  java.util.List<? extends com.doubleknd26.filmography.proto.ReviewOrBuilder> 
      getReviewsOrBuilderList();
  /**
   * <code>repeated .Review reviews = 5;</code>
   */
  com.doubleknd26.filmography.proto.ReviewOrBuilder getReviewsOrBuilder(
      int index);
}
