// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filmography.proto

package com.doubleknd26.filmography.proto;

public interface ReviewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Review)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string url = 2;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 2;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>float grade = 3;</code>
   */
  float getGrade();

  /**
   * <code>string comment = 4;</code>
   */
  java.lang.String getComment();
  /**
   * <code>string comment = 4;</code>
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <code>int64 timestamp = 5;</code>
   */
  long getTimestamp();

  /**
   * <code>.Source source = 99;</code>
   */
  int getSourceValue();
  /**
   * <code>.Source source = 99;</code>
   */
  com.doubleknd26.filmography.proto.Source getSource();
}
