// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filmography.proto

package com.doubleknd26.filmography.proto;

/**
 * Protobuf enum {@code Source}
 */
public enum Source
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TEST = 0;</code>
   */
  TEST(0),
  /**
   * <code>NAVER = 1;</code>
   */
  NAVER(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TEST = 0;</code>
   */
  public static final int TEST_VALUE = 0;
  /**
   * <code>NAVER = 1;</code>
   */
  public static final int NAVER_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Source valueOf(int value) {
    return forNumber(value);
  }

  public static Source forNumber(int value) {
    switch (value) {
      case 0: return TEST;
      case 1: return NAVER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Source>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Source> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Source>() {
          public Source findValueByNumber(int number) {
            return Source.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.doubleknd26.filmography.proto.Filmography.getDescriptor().getEnumTypes().get(0);
  }

  private static final Source[] VALUES = values();

  public static Source valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Source(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Source)
}

